name: CD - FAST Creator

on:
  push:
    branches:
    - release

jobs:
  build_deploy_linux:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_ACTIVE_STAGE_NAME: create-west-app
      AZURE_WEBAPP_PASSIVE_STAGE_NAME: create-east-app
      AZURE_WEBAPP_DIST_PATH: www
      AZURE_WEBAPP_SLOT_NAME: stage
    
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: release

    - name: Build & Prepare Web Application
      run: |
        npm i --legacy-peer-deps
        cp build/server/* ./www 
        cd www
        npm i
        ls -lta

    - name: 'Deploy to Active Azure Region'
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CREATE_ACTIVE }}
        app-name: ${{ env.AZURE_WEBAPP_ACTIVE_STAGE_NAME }}
        package: ${{ env.AZURE_WEBAPP_DIST_PATH }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}

    - name: 'Deploy to Passive Azure Region'
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CREATE_PASSIVE }}
        app-name: ${{ env.AZURE_WEBAPP_PASSIVE_STAGE_NAME }}
        package: ${{ env.AZURE_WEBAPP_DIST_PATH }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}