name: Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
    - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x]

    env:
      AZURE_WEBAPP_NAME: creator-app
      AZURE_WEBAPP_SLOT_NAME: stage
      ARTIFACT_NAME: creator-app-stage

    steps:
    - uses: actions/checkout@v2
      with:
        ref: release
    - uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node version ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Build & prepare web application
      run: |
        npm ci --ignore-scripts
        npm run build
        cp build/server/* www
        cd www
        npm ci
        ls -lta
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: www
       
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:    
    - uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CREATOR }}
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
        package: '.'

  notify:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Notify on Discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_NOTIFICATION_WEBHOOK_TOKEN }}
        color: '#DE2D6D'
        username: 'FAST DevOps Creator Bot'
        message: 'Deployment has completed to Staging on https://github.com/microsoft/fast-creator/actions/workflows/cd-deploy-staging.yml'
        
