name: CI - FAST Creator

on:
  push:
    branches: 
      - release
  pull_request:
    branches: 
      - release 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: release

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Test
      run: npm run test
        
       